{% set name = "ParmEd" %}
{% set version = "3.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: "42e031683f0ba63d70300306017b6eb882e4f0a2098034b78b4640360f8dd6c4"

build:
  number: 1
  entry_points:
    - parmed = parmed.scripts:clapp
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win and vc<14]

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pip
    - python
  run:
    - numpy >=1.14
    - pandas
    - python

test:
  imports:
    - parmed
    - parmed.amber
    - parmed.amber.mdin
    - parmed.charmm
    - parmed.formats
    - parmed.formats.pdbx
    - parmed.gromacs
    - parmed.modeller
    - parmed.namd
    - parmed.openmm
    - parmed.rdkit
    - parmed.rosetta
    - parmed.tinker
    - parmed.tools
    - parmed.tools.gui
    - parmed.tools.simulations
    - parmed.unit
    - parmed.utils
    - parmed.utils.fortranformat
  commands:
    - parmed --help

about:
  home: "https://parmed.github.io/ParmEd/html/index.html"
  license: "LGPL (or GPL if released with AmberTools)"
  license_family: "LGPL"
  license_file: "LICENSE"
  summary: "Amber parameter file editor"
  doc_url: "https://parmed.github.io/ParmEd/html/index.html"
  description: |
    ParmEd is a package designed to facilitate creating and easily manipulating molecular systems that are fully described by a common classical force field. Supported force fields include Amber, CHARMM, AMOEBA, and several others that share a similar functional form (e.g., GROMOS).

extra:
  recipe-maintainers:
    - chrisbarnettster
    - simonbray
    - tsenapathi
    - jaimergp
